# Generated by Django 6.0.4 on 2026-05-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_reporter',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access reports but not admin features.', verbose_name='Lekérdező'),
        ),
    ]
