# Generated by Django 6.0.4 on 2026-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='A felületen minden funkcióhoz hozzáfér (Projektek, Partnerek, Felhasználók stb.), de nem Django site admin.', verbose_name='Cégvezető / Admin'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_reporter',
            field=models.BooleanField(default=False, help_text='Csak a riportokhoz fér hozzá.', verbose_name='Lekérdező (Könyvelő)'),
        ),
    ]
