# Generated by Django 6.0.4 on 2026-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_company_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='annual_leave_allowance',
            field=models.IntegerField(blank=True, help_text='Csak alkalmazott esetén értelmezett.', null=True, verbose_name='Éves szabadságkeret (nap)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employment_type',
            field=models.CharField(choices=[('employee', 'Alkalmazott'), ('contractor', 'Vállalkozó')], default='contractor', max_length=20, verbose_name='Jogviszony'),
        ),
    ]
