# Generated by Django 6.0.4 on 2026-06-08 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_options_alter_client_address_and_more'),
        ('projects', '0003_alter_project_options_alter_project_assigned_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['client__name', 'name'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projektek'},
        ),
        migrations.AddField(
            model_name='project',
            name='max_daily_hours',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4, verbose_name='Max napi könyvelhető óraszám'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Hozzárendelt tanácsadók'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Befejezés Dátuma'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Projekt Név'),
        ),
    ]
