# Generated by Django 6.0.4 on 2026-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_project_max_daily_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_daily_hours',
            field=models.IntegerField(default=8, verbose_name='Max napi könyvelhető óraszám'),
        ),
    ]
