# Generated by Django 6.0.4 on 2026-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_max_daily_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='calendar',
            field=models.CharField(choices=[('hu', 'Magyar'), ('at', 'Osztrák')], default='hu', help_text='A projekt munkaszüneti napjait és munkarendjét határozza meg.', max_length=2, verbose_name='Naptár / Ország'),
        ),
    ]
