# Generated by Django 6.0.4 on 2026-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='calendar',
            field=models.CharField(choices=[('hu', 'Magyarország'), ('at', 'Ausztria')], default='hu', help_text='A projekt munkaszüneti napjait és munkarendjét határozza meg.', max_length=2, verbose_name='Naptár'),
        ),
    ]
