# Generated by Django 6.0.4 on 2026-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Dátum')),
                ('description', models.CharField(max_length=200, verbose_name='Megnevezés/Leírás')),
                ('is_working_day', models.BooleanField(default=False, help_text='Jelöld be, ha ez egy áthelyezett munkanap (pl. egy szombat, ami munkanap).', verbose_name='Kivétel (Munkanap)')),
            ],
            options={
                'verbose_name': 'Ünnepnap / Kivétel nap',
                'verbose_name_plural': 'Ünnepnapok és Kivételek',
                'ordering': ['date'],
            },
        ),
    ]
