# Generated by Django 6.0.4 on 2026-06-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_alter_holiday_options_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Ünnepnap / Pihenőnap', 'verbose_name_plural': 'Ünnepnapok / Pihenőnapok'},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_working_day',
            field=models.BooleanField(default=False, help_text='Jelöld be, ha ez egy pihenőnapra eső áthelyezett munkanap (pl. munkanap szombat).', verbose_name='Áthelyezett munkanap'),
        ),
    ]
