# Generated by Django 6.0.4 on 2026-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_alter_holiday_options_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='calendar',
            field=models.CharField(choices=[('hu', 'Magyar'), ('at', 'Osztrák')], default='hu', max_length=2, verbose_name='Naptár / Ország'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(verbose_name='Dátum'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('calendar', 'date')},
        ),
    ]
