# Generated by Django 6.0.4 on 2026-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_holiday_calendar_alter_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='calendar',
            field=models.CharField(choices=[('hu', 'Magyar'), ('at', 'Osztrák')], default='hu', max_length=2, verbose_name='Naptár'),
        ),
    ]
