# Generated by Django 6.0.4 on 2026-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_alter_holiday_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='calendar',
            field=models.CharField(choices=[('hu', 'Magyarország'), ('at', 'Ausztria')], default='hu', max_length=2, verbose_name='Naptár'),
        ),
    ]
