# Generated by Django 6.0.4 on 2026-05-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_is_active'),
        ('timesheet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(verbose_name='Hónap')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Érték')),
                ('unit', models.CharField(choices=[('days', 'Nap'), ('hours', 'Óra')], default='days', max_length=10, verbose_name='Mértékegység')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_certificates', to='clients.client', verbose_name='Partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Partner TIG',
                'verbose_name_plural': 'Partner TIG-ek',
                'unique_together': {('user', 'client', 'year', 'month')},
            },
        ),
    ]
