# Generated by Django 6.0.4 on 2026-06-08 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_project_max_daily_hours_and_more'),
        ('timesheet', '0002_clientcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date', 'project__name'], 'verbose_name': 'Munkaóra', 'verbose_name_plural': 'Munkaórák'},
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='date',
            field=models.DateField(verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Órák'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Tanácsadó'),
        ),
    ]
