# Generated by Django 6.0.4 on 2026-05-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_city_client_contact_name_client_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='Hungary', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
    ]
