# Generated by Django 6.0.4 on 2026-06-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partnerek'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Város'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kapcsolattartó neve'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kapcsolattartó telefonja'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Szerződésszám'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='Hungary', max_length=100, verbose_name='Ország'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Irányítószám'),
        ),
    ]
