# Generated by Django 6.0.4 on 2026-05-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Kezdő dátum')),
                ('end_date', models.DateField(verbose_name='Befejező dátum')),
                ('leave_type', models.CharField(choices=[('SZI', 'Szabadság'), ('BET', 'Betegszabadság'), ('FMT', 'Fizetés nélküli távollét')], default='SZI', max_length=3, verbose_name='Típus')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Távollét',
                'verbose_name_plural': 'Távollétek',
                'ordering': ['-start_date'],
            },
        ),
    ]
