# Generated by Django 6.0.4 on 2026-05-02 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start_date'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('PTO', 'Paid Time Off'), ('SIC', 'Sick Leave'), ('UNP', 'Unpaid Leave')], default='PTO', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
