# Generated by Django 6.0.4 on 2026-05-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leave_options_alter_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('PTO', 'Paid Time Off (PTO)'), ('SIC', 'Sick Leave'), ('UNP', 'Unpaid Leave')], default='PTO', max_length=3, verbose_name='Type'),
        ),
    ]
