# Generated by Django 6.0.4 on 2026-06-08 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leave_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start_date'], 'verbose_name': 'Szabadság', 'verbose_name_plural': 'Szabadságok'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(verbose_name='Befejezés dátuma'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('PTO', 'Fizetett Szabadság'), ('SIC', 'Betegszabadság'), ('UNP', 'Fizetés Nélküli Szabadság')], default='PTO', max_length=3, verbose_name='Típus'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Megjegyzés'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(verbose_name='Kezdés dátuma'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL, verbose_name='Tanácsadó'),
        ),
    ]
